services:
  reverse_proxy:
    image: traefik:2.11
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --entryPoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.address=:80
      - --log.filePath=/configuration/logs/traefik.log
      - --log.format=json
      - --accesslog=true
      - --accesslog.filepath=/configuration/logs/access.log
      - --accesslog.format=json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      # - "6000:6000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./_local_traefik_config/traefik.toml:/etc/traefik/traefik.toml:ro
      - /Users/ben/traefik:/configuration
    deploy:
      labels:
        - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
        - traefik.http.routers.http-catchall.entrypoints=web
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      replicas: 2
    networks:
      - traefik


networks:
  traefik:
    name: traefik-proxy
    external: true