# Generated by Django 5.1.2 on 2024-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_soiled", "0002_rename_moisure_percent_measurement_moisture_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
