# Generated by Django 5.1.2 on 2024-10-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_soiled", "0003_alter_sensor_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={
                "get_latest_by": "created_at",
                "verbose_name": "Measurement",
                "verbose_name_plural": "Measurements",
            },
        ),
        migrations.AlterField(
            model_name="sensor",
            name="mac_address",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
