# Generated by Django 5.1.4 on 2024-12-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_feature_flags', '0002_feature_enable_at_feature_remove_old_func_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='enable_at',
            field=models.DateTimeField(blank=True, help_text="If 'active', feature will enable at this date and time.", null=True),
        ),
    ]
