# Generated by Django 5.1.4 on 2024-12-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_feature_flags', '0003_alter_feature_enable_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature Flag', 'verbose_name_plural': 'Feature Flags'},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='enable_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='options',
        ),
    ]
