# Generated by Django 5.1.4 on 2024-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_feature_flags', '0004_alter_feature_options_remove_feature_enable_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
