# Generated by Django 5.1.4 on 2024-12-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_feature_flags', '0005_alter_feature_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='desciption',
            new_name='description',
        ),
    ]
