[api]
dashboard = true
insecure = true

[entryPoints]
    [entryPoints.http]
    address = ":80"

    [entryPoints.websecure]
    address = ":443"

[providers]
    [providers.docker]
    # endpoint = "unix:///var/run/docker.sock"
#   defaultRule = "Host(`{{ normalize .Name }}.example.com`)"
#   exposedByDefault = false
    network = "web"
    swarmMode = true


# defaultEntryPoints = ["http", "https"]

# [entryPoints]
#     [entryPoints.http]
#     address = ":80" 
#         [entryPoints.http.redirect]
#         entryPoint = "https"
#     [entryPoints.https]
#     address = ":443"
#     [entryPoints.https.tls]
#       [[entryPoints.https.tls.certificates]]
#       certFile = "/etc/traefik/ssl/_wildcard.project1.com.pem"
#       keyFile = "/etc/traefik/ssl/_wildcard.project1.com-key.pem"
#       [[entryPoints.https.tls.certificates]]   # repeat this block to add more SSL certificates
#       certFile = "/etc/traefik/ssl/_wildcard.project2.com.pem"
#       keyFile = "/etc/traefik/ssl/_wildcard.project2.com-key.pem"

# [api]

# [docker]